# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

#Configuring Ubuntu
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty64"
    ubuntu.vm.hostname = "ubuntu-aarjvi"
    ubuntu.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", type: "dhcp"
    ubuntu.vm.network "forwarded_port", guest: 80, host: 8080
  end

#Configuring Centos
  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos-aarjvi"
    centos.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", type: "dhcp"
    centos.vm.network "forwarded_port", guest: 80, host: 8081
  end

end
